#!/bin/bash
source config.sh

#   Sees if venv exists already, loads venv if so
if [ -d "$pythonVENV" ]; then
    echo "\"$pythonVENV\" does exist."
    source $venvScript

#   Sets up venv and then loads it
else
    #   Create the virtual environment
    # install dependencies
    bash install
    #   Access the venv
    source $venvScript
fi

$pythonCmd $@

#echo "root:: $root"
#echo "pythonVenv: $pythonCmd"