#!/bin/bash
root=$(pwd)
pythonVENV=$root/.venv
venvScript=$pythonVENV/bin/activate
pythonCmd=$pythonVENV/bin/python3

#   Sees if venv exists already, loads venv if so
if [ -d "$pythonVENV" ]; then
    echo "\"$pythonVENV\" does exist."
    # source $venvScript

#   Sets up venv and then loads it
else
    #   Create the virtual environment
    python3 -m venv $pythonVENV
    #   Access the binary
    source $venvScript
    #   Install dependencies
    pip install -r $venvRequirements
    genHeader "Python loaded/dependencies installed" $BASH_SEPERATOR_MAJOR
fi

$pythonCmd $root/main.py $@

#echo "root:: $root"
#echo "pythonVenv: $pythonCmd"